# -*- coding: utf-8 -*-
"""Nlp_indian-regional -languageTranslator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t7b70VxnBW3BctQNhcDL_sanDhuizr4H
"""

pip install nltk

pip install googletrans==4.0.0-rc1

from googletrans import Translator

def translate_to_indian_language(text, target_language):
    translator = Translator()
    translation = translator.translate(text, dest=target_language)
    return translation.text

# Map Indian language codes to their respective names
indian_languages = {
    'hi': 'Hindi',
    'ta': 'Tamil',
    'te': 'Telugu',
    'kn': 'Kannada',
    'mr': 'Marathi',
    'gu': 'Gujarati',
    'pa': 'Punjabi',
    'bn': 'Bengali',
    'ur': 'Urdu',
    'ml': 'Malayalam',
    # Add more Indian language codes and names as needed
}

# Take user input
user_input = input("Enter the text in English: ")

# Choose the target Indian language
print("Select a target Indian language:")
for code, name in indian_languages.items():
    print(f"{code}: {name}")

target_language = input("Enter the code of the target Indian language: ")

if target_language in indian_languages:
    translated_text = translate_to_indian_language(user_input, target_language)
    print(f"Translated text in {indian_languages[target_language]}: {translated_text}")
else:
    print("Invalid language code. Please choose a valid Indian language code.")